### ISSUE TITLE
Throt/Markus/Grimgor - Mission Aborted - Replace RAZE with OCCUPY

### ISSUE THREAD

**Issue by Mjb141** [msolefonte/vco#141]
I started a new Throt campaign today, and at about turn 15 I got a notification for "Mission aborted". It was for the second victory condition. 2 of the 4 Settlements needed have been razed, and Both Kislev factions are still alive. The victory condition has a checkmark next to it now indicating it is done, but I don't have the rewards. Will play more and if I fulfill the conditions I'll update whether I get the rewards then or not.

**Comment by msolefonte** [comment]
@Mjb141 Can you check this one?

**Comment by Mjb141** [comment]
I can take a look.

**Comment by OhManTFE** [comment]
What even is "mission aborted". That's for missions. This whole mod doesn't even touch the mission system, right? Just victory objectives only?

**Comment by msolefonte** [comment]
A Victory Objective is a glorified mission

**Comment by OhManTFE** [comment]
Yeh but I'm talking about game systems; aren't they separate?

**Comment by msolefonte** [comment]
> Yeh but I'm talking about game systems; aren't they separate?

No. For the engine it is the same. A victory condition is just a mission that triggers a victory as a payload.

**Comment by Mjb141** [comment]
Ok I just played (read: end-turned) a Throt campaign to turn 30. The route isn't abandoned or completed. I'd suggest we tidy this route up (flavour text in another ticket, raze or sack including fix) and wait and see if more reports show up.

**Comment by msolefonte** [comment]
Same than with the other one. Next time we get a report, we ask for the savegame or for logs.

**Comment by OhManTFE** [comment]
Another steam commenter solved this issue. Ironically we inadvertently fixed this issue by changing to OCCUPY instead of RAZE anyway.

Reason it is intermittent is AI has to raze one of the settlements the objective specifies. You can't raze a settlement that is already razed, and so ta da the mission is failed.

Solution: We can't use this raze objective type. From memory it's also in use for markua wulfhart and grimgor.

We should stick with occupy.

Raze objective was also problematic for gameplay reasons so I personally am happy this has happened. :)

**Comment by Mjb141** [comment]
So this is fixed by https://github.com/msolefonte/vco/pull/176/files#diff-6f6b37f63f33e89e9d3baa8abcf5c569655101ff5d6773bbde453a5c11b860ba ? If so I'll close this.

**Comment by OhManTFE** [comment]
Yeh but we need to swap out Markus Wulfhart and Grimgor's raze objectives.

**Comment by msolefonte** [comment]
Closed as we already have an issue for Markus & Grimgor.

**Comment by OhManTFE** [comment]
Fixed up nice.
