### ISSUE TITLE
CST - Pirates of Sartosa

### ISSUE THREAD

**Issue by msolefonte** [msolefonte/vco#51]
## Aranessa Saltspite: Pirates of Sartosa

* **Route I - Captain of the Swordfysh** 
  * Commander of the Swordfysh, a mighty galleon crewed by hundreds, Aranessa and her crew prefer boarding actions to thundering broadsides. The ship roves the Tilean Sea and beyond, raiding and pillaging all who cross its path. Make them all fear the crossed tridents upon its sails.
    * Accrue 20000 fame
    * Earn 15000 from raiding
  * **The Pirate Queen**: (tech_cst_command_00.png)
    * Income from Pirate Coves +25%
    * Movement range after winning a battle +25%
  * Do you know what she, the queen of the pirates, did when the treasure she had always searched for was placed before her very eyes? She laughed.

* **Route II - Daughter of Manann** 
  * Rumour has it that saltwater flows through her veins instead of blood. That she rose fully grown from the waves in a froth of gore. The truth, unknown to most, is not so magnificent - Aranessa was born a mutant in Skjold and thrown into the sea by her own Norscan tribe. Her crews and victims alike believe Manann, Lord of the Seas, watches over her, and the seas rage as the Swordfysh sails into the wealthiest ports.
    * Raze/Sack 8 settlements from:
      * region wh3_main_combi_region_myrmidens;
                    region wh3_main_combi_region_bordeleaux;
                    region wh3_main_combi_region_lyonesse;
                    region wh3_main_combi_region_erengrad;
                    region wh3_main_combi_region_marienburg;
                    region wh3_main_combi_region_altdorf;
                    region wh3_main_combi_region_lothern;
                    region wh3_main_combi_region_the_awakening;
                    region wh3_main_combi_region_citadel_of_dusk;
                    region wh3_main_combi_region_the_twisted_glade;
                    region wh3_main_combi_region_naggarond;
                    region wh3_main_combi_region_fortress_of_the_damned;
    * Build Landmark:
      * Dragon Tooth Lighthouse
  * **Lady of the Seas**: (tech_cst_blockading_the_vampire_coast.png)
    * +2500 fame
    * +12 melee attack for all units whilst at sea
    * +12 leadership for all units whilst at sea
  * Manann is said to be mighty, called the Summoner of Storms, and Master of Maelstroms.... But no-one ever said he pays the crews wages. For that, you need plunder - and lots of it!
  * **Manann Provides**
    * 50% upkeep reduction for all Rotting Leviathans and Rotting Prometheans
  * Many a sea beast has died at sea, their corpses sinking gracefully to the sea bed. Aranessa's vampire first mate is all too happy to raise those corpses as fodder for her beloved captain.

* **Route III - Dead Man's Vengeance**
  * "You'll have your vengeance, Jaego. I'll see it done."
    * Destroy factions: 
      * The Dreadfleet
    * Raze/Sack settlements:
      * Galleon's Graveyard
  * **Sank the Bloody Reaver**: (tech_cst_command_03.png)
    * +2500 fame
    * +20% missile strength for zombie pirate units
  * Minds filled with vengeance, eyes filled with hatred, hearts filled with satisfaction... The sacking of Sartosa has been repaid tenfold, and the undead of Count Noctilus, once Nyklaus Von Carstein, lie still again.
  * **Master of the Colossi** (tech_cst_firearms_06.png)
    * Recruitment duration -1 for Necrofex Colossus
    * Upkeep -33% for Necrofex Colossus 
  * The seas are a better place without the Dreadfleet and its ferocious captain, but his mastery of the Necrofex Colossi was impressive. Such knowledge should not sink beneath the waves.

**Comment by msolefonte** [comment]
@MichaelBrown08 Do you want to assume the design of this one once you are done with the current release?

**Comment by MichaelBrown08** [comment]
I can do yep, played a bunch of Aranessa so I'll get onto it on Friday!

**Comment by MichaelBrown08** [comment]
Interesting, thematic effects for Pirates of Sartosa:

- Cove mods, since Sartosa largely plays tall with coves/raiding
  - wh2_dlc11_effect_agent_action_hinder_settlement_establish_pirate_cove_cost_mod (cheaper coves)
  - wh2_dlc11_effect_cove_income_gdp_mod (income boost from coves)
  - wh2_dlc11_effect_agent_action_success_chance_dignitary_establish_pirate_cove
- Sartosa unit mods, since Aranessa boosts them
  - wh2_dlc11_cst_recruit_xp_sartosa_free_company
  - wh2_dlc11_effect_force_stat_leadership_sartosa_free_company
  - wh2_dlc11_effect_force_stat_melee_attack_sartosa_free_company
  - wh2_dlc11_effect_force_stat_melee_defence_cst_sartosa_free_company
- Melee attack/defense / weapon strength vs vampire coast, due to competition/rivalry between pirates (both need copying into versions without tomb kings)
  - wh2_dlc13_effect_melee_attack_versus_vmp_cst_tmb
  - wh2_dlc13_effect_melee_defence_versus_vmp_cst_tmb
  - wh2_dlc13_effect_force_stat_weapon_strength_vs_nor_chs_bst (copy needed for vampire coast in effect_bonus_value_battle_context_junctions_tables)
- Ammunition mods, vampire coast are heavy gunpowder users
  - wh2_dlc11_effect_force_stat_ammunition_cst_artillery
  - wh2_dlc11_effect_force_stat_ammunition_cst_ranged_infantry
- Economic buffs useful to a tall faction
  - wh2_dlc11_effect_campaign_sacking_income_vampire_counts (copy needed for vampire coast in effect_bonus_value_subculture_junctions_table)
  - wh2_main_effect_economy_gdp_mod_trade_sea_global (Sartosa has multiple resources, ports often have more that Aranessa can easily get to)
- Infamy
  - wh2_dlc11_pooled_resource_infamy_other (copy needed for new source of infamy)

**Comment by msolefonte** [comment]
I disabled all notifications but here I am lol please ban me.

Do not worry about being limited by particular effects. It is fine to use the defined ones for inspiration (or product), but I can always create new custom and tailored stuff. In any case, I always like to add pooled resources as rewards for those factions that have them as objectives. Something like: Route 1: Requires 20000 Infamy, Route II Reward: +2000 Infamy, Route III Reward: +2000 Infamy.

**Comment by Mjb141** [comment]
Route 2 obj: RAZE_OR_SACK_N_DIFFERENT_SETTLEMENTS_RELIGION, key

**Comment by OhManTFE** [comment]
Fixed typos and sentence structure of flavour text. (Mission objectives, rewards).

Needs to be inputted into the packfile itself.
